# Generated by Django 4.2.3 on 2023-07-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('polity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('science_technology', models.DecimalField(decimal_places=2, max_digits=5)),
                ('art_culture', models.DecimalField(decimal_places=2, max_digits=5)),
                ('history', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maths', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reasoning', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ethics', models.DecimalField(decimal_places=2, max_digits=5)),
                ('geography', models.DecimalField(decimal_places=2, max_digits=5)),
                ('literature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('economics', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
